### ISSUE TITLE
All my MANIFEST.APP entries disappeared!

### ISSUE THREAD

**Issue by danbromberg** [jonathontoon/memgrid#361]
## Current Behavior
When I ran CCLEANER it deleted all my MANIFEST entries! Maybe that was to be expected and maybe I'll remember for the next time, or maybe I should just use GOOGLE KEEP which doesn't get deleted and expands to more than one screen.

**Comment by danbromberg** [comment]
I don't suppose there is a way to retrieve what got deleted.

**Comment by KiraScurro** [comment]
i have the same question. i just lost all my entries when i purged all my cookies.

**Comment by jonathontoon** [comment]
@danbromberg @KiraScurro Hi there. While I'm not actively maintaining this repository right now, I'm sorry that you lost your notes! Because the data is stored in your browser's local storage wiping browser settings like cookies may also trigger a wipe of the local storage is well.
